# IB Gateway configuration
ib_gateway:
  host: 127.0.0.1
  port: 4002
  client_id: 1
  account: "DU1234567"

# Application settings
dry_run: True
markets_enabled: ["FX", "FUT", "CRYPTO", "STK", "OPT"]
scheduler_windows:
  - {start: "08:00", end: "16:00"}
risk_limits:
  max_daily_loss_pct: 0.05
  risk_per_trade_pct: 0.01
pdt_enabled: True

# Security
api_key: "your-secret-api-key"